title: GetControl <img src="img/GetControl-32.png" />
description: Program for collecting data and facilitating the structural refinement using the FullProf package.
remote_theme: pages-themes/slate@v0.2.0
show_downloads: false
